# Generated by Django 3.1.2 on 2020-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='p_no',
            field=models.CharField(max_length=50),
        ),
    ]
