# Generated by Django 3.1.2 on 2020-11-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0002_auto_20201106_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Couresecs',
            new_name='Courses_for_arts',
        ),
        migrations.RenameModel(
            old_name='Couresea',
            new_name='Courses_for_commers',
        ),
        migrations.RenameModel(
            old_name='Coureses',
            new_name='Courses_for_commersANDsci',
        ),
        migrations.RenameModel(
            old_name='Couresec',
            new_name='Courses_for_sci',
        ),
    ]
