# Generated by Django 3.1.2 on 2020-11-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0003_auto_20201108_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses_for_commersANDsci',
            new_name='Courses_for_commersPlusMaths',
        ),
    ]
