# Generated by Django 3.1.2 on 2020-11-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0006_auto_20201108_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_for_arts',
            name='pho',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
