# Generated by Django 3.1.2 on 2020-11-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0008_auto_20201119_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_for_commers',
            name='pho',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='courses_for_commersplusmaths',
            name='pho',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
