# Generated by Django 3.1.2 on 2020-11-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0009_auto_20201119_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='maths_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
