# Generated by Django 3.1.2 on 2020-11-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0010_auto_20201127_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='persontage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
