# Generated by Django 3.1.2 on 2020-11-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0011_auto_20201127_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newevent',
            old_name='dat',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='newevent',
            old_name='tim',
            new_name='post_time',
        ),
        migrations.AddField(
            model_name='newevent',
            name='event_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newevent',
            name='event_time',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newevent',
            name='pho',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_no',
            field=models.CharField(max_length=10),
        ),
    ]
