# Generated by Django 3.1.2 on 2020-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0012_auto_20201128_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pho', models.ImageField(upload_to='media/')),
                ('new_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('post_time', models.TimeField(max_length=50)),
                ('post_date', models.DateField(max_length=50)),
                ('quote', models.TextField(max_length=50)),
                ('dis', models.TextField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='newevent',
            old_name='tit',
            new_name='title',
        ),
    ]
