# Generated by Django 3.1.2 on 2020-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0013_auto_20201128_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
        migrations.AddField(
            model_name='newevent',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
