# Generated by Django 3.1.2 on 2020-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saket', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='button',
            field=models.CharField(blank=True, choices=[('Download', 'Download'), ('Apply', 'Apply')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
